# Generated by Django 5.2 on 2025-04-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="../default_profile_b6krcy", upload_to="images/"
            ),
        ),
    ]
